name: Build and Push Docker Image(s)

on:
  push:
    branches:
      - main
    paths:
      - 'BESST/loginbypass/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          cd BESST/loginbypass
          docker buildx create --driver docker-container --use
          docker compose build --pull --push loginbypass
          docker buildx rm
